name: deploy

on:
  push:
    branches:
      - master


jobs:
  test:
    runs-on: ubuntu-22.04
    needs: test
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Node.js setup
        uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: Install npm packages
        run: npm ci
      - name: install and run redis-server
        run: |
          sudo apt-get update
          sudo apt-get install -y redis-server
          redis-server --daemonize yes --requirepass test_env --port 6380
      - name: Run test
        run: npm run test:ci

      - name: test build
        run: npm run build


  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_SECRET_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Set up known Hosts
        run: |
          echo "${{ secrets.SSH_KNOWN_HOSTS }}" >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      - name: SSH and deploy
        run: |
          ssh "${{ secrets.SSH_USERNAME }}"@${{ secrets.SSH_PUBLIC_IP }} "
          cd ecs-express
          git pull || exit 1
          npm install || exit 1
          npm run build || exit 1
          sudo pkill node || exit 1
          sudo npm run start & npx wait-on http://localhost
          exit
          "